version: '3'
services:

  messaging:
    image: 'rabbitmq:3-management'
    ports:
      - 5672:5672
      - 15672:15672
      
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
      
  front_end:
    build: ./frontend
    ports:
        - 5000:5000
