version: '3'
services:
  messaging:
    image: 'rabbitmq:3-management'
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: changeme
  front_end:
    build: ./front_end
    ports:
        - 5000:5000
